---
consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:9100"
        interval: "10s"
  - name: "nginx-exporter"
    id: "nginx-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:8080"
        interval: "10s"
  - name: "timescale"
    id: "timescale"
    address: "{{ private_ip }}"
    port: 5432
    checks:
      - tcp: "{{ private_ip }}:5432"
        interval: "10s"
