---
- name: Bootstrap basic
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - dev-sec.ssh-hardening
    - dev-sec.os-hardening
    - local.common-packages
    - brianshumate.consul
    - cloudalchemy.node-exporter
  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted
        sleep: 5
  tasks:
    - name: Deploy dhclient.conf
      copy:
        dest: /etc/dhcp/dhclient.conf
        src: files/dhclient.conf
        backup: true
        mode: 0644
        owner: root
        group: root
      notify: restart networking
