---
- name: Bootstrap basic
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  collections:
    - devsec.hardening
  roles:
    - devsec.hardening.os_hardening
    - devsec.hardening.ssh_hardening
    - local.common-packages
    - cloudalchemy.node-exporter
  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted
        sleep: 5
  tasks:
    - name: Deploy extra authorized keys
      authorized_key:
        user: "{{ item.value.user|default(ansible_ssh_user) }}"
        key: "{{ item.value.key }}"
        state: present
        key_options: "{{ item.value.key_options|default(omit) }}"
        comment: "{{ item.value.comment|default(omit) }}"
      loop: "{{ extra_authorized_keys|default({})|dict2items }}"

    - name: Deploy dhclient.conf
      copy:
        dest: /etc/dhcp/dhclient.conf
        src: files/dhclient.conf
        backup: true
        mode: 0644
        owner: root
        group: root
      notify: restart networking
