---
- name: Install loadbalancer
  hosts: meta-role_lb
  any_errors_fatal: true
  become: true
  become_user: root
  tasks:
    - name: Install haproxy
      apt:
        name: haproxy
        state: present
  roles:
    - griggheo.consul-template
    - bdellegrazie.haproxy_exporter
