---
- name: Configure PostgreSQL
  hosts: meta-role_postgresql_server
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - local.pgdg
    - geerlingguy.postgresql
    - local.timescaledb
