---
- name: Boostrap prometheus
  hosts: meta-subrole_prometheus
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - cloudalchemy.prometheus
  tasks:
    - name: Add fake entry in /etc/hosts
      lineinfile:
        dest: /etc/hosts
        # yamllint disable-line rule:line-length
        line: "{{ hostvars.tsbs.openstack | json_query('addresses.*[].addr') | ipaddr('10.0.0.0/8') | first }} node-{{ item }}"
        regexp: 'node-{{ item }}$'
        state: present
      loop: "{{ range(fake_targets_count)|list }}"

    - name: Create file_sd_config file
      template:
        src: bench-file-sd-config.yml.j2
        dest: /etc/prometheus/file_sd/bench-file-sd-config.yml
        owner: root
        group: prometheus
        mode: 0644
      notify: reload prometheus
