---
- name: Boostrap prometheus
  hosts: meta-subrole_prometheus
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - cloudalchemy.prometheus
  tasks:
    - name: Create file_sd_config file
      template:
        src: bench-file-sd-config.yml.j2
        dest: /etc/prometheus/file_sd/bench-file-sd-config.yml
        owner: root
        group: prometheus
        mode: 0644
      vars:
        # yamllint disable-line rule:line-length
        fake_ips: "{{ groups['meta-subrole_tsbs'] | map('extract', hostvars, ['openstack', 'addresses'])|list|json_query('[].*[][][].addr')| ipaddr('10.0.0.0/8') }}"
      notify: reload prometheus
      when: groups.get('meta-subrole_tsbs')

    - include_tasks: tasks/grafana-annotation-create.yml
      run_once: true
      vars:
        annotation_text: |
          prometheus_count: {{ groups.get('meta-subrole_prometheus', [])|length }}
          fake_target: {{ fake_targets_count }}
          prometheus_remote_write: {{ prometheus_remote_write | to_nice_yaml }}
        annotation_tags:
          - prometheus
