---
roles:
  - name: brianshumate.consul
    version: v2.5.4
  - name: geerlingguy.postgresql
    version: 3.1.0
  - name: andrewrothstein.go
    version: v2.1.48
  - name: cloudalchemy.grafana
    version: 0.18.0
  - name: cloudalchemy.prometheus
    version: 3.0.0
  - name: cloudalchemy.node_exporter
    version: 2.0.0
  - name: kostiantyn-nemchenko.patroni
    version: v1.0.1
  - name: slapper.ansible_victoriametrics_cluster_role
    version: 291a9b6
    src: https://github.com/Slapper/ansible-victoriametrics-cluster-role.git
  - name: bdellegrazie.postgres_exporter
    version: v4.1.1
  - name: bdellegrazie.haproxy_exporter
    version: v1.4.0
  - name: griggheo.consul-template
    version: ff5bcde
    src: https://github.com/griggheo/ansible-consul-template.git
  - name: bdellegrazie.nginx_exporter
    version: v3.2.0
  - name: diogenxs.loki
    src: https://github.com/diogenxs/ansible-role-loki.git
    version: f74de4a
  - name: andrewrothstein.etcd-cluster
    version: v2.0.0

collections:
  - name: devsec.hardening
    version: 7.5.0
  - name: nginxinc.nginx_core
    version: 0.3.0
