---
roles:
  - name: brianshumate.consul
    version: v2.5.4
  - name: geerlingguy.postgresql
    version: 2.2.1
  - name: andrewrothstein.go
    version: v2.1.37
  - name: cloudalchemy.grafana
    version: 0.18.0
  - name: cloudalchemy.prometheus
    version: 2.15.5
  - name: cloudalchemy.node-exporter
    version: 0.21.5
  - name: kostiantyn-nemchenko.patroni
    version: v1.0.0
  - name: slapper.ansible_victoriametrics_cluster_role
    # Using fork as upstream does not allow to specify which address to listen to
    # see: https://github.com/Slapper/ansible-victoriametrics-cluster-role/pull/2
    version: c7946b3
    src: https://github.com/wilfriedroset/ansible-victoriametrics-cluster-role.git
  - name: bdellegrazie.postgres_exporter
    version: v4.1.0
  - name: bdellegrazie.haproxy_exporter
    version: v1.3.2
  - name: griggheo.consul-template
    version: ff5bcde
    src: https://github.com/griggheo/ansible-consul-template.git
  - name: bdellegrazie.nginx_exporter
    version: v3.2.0

collections:
  - name: devsec.hardening
    version: 7.0.0
  - name: nginxinc.nginx_core
    version: 0.3.0
