---
- name: Bootstrap basic
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - local.common-packages
    - brianshumate.consul
  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted
        sleep: 5
  tasks:
    - name: Disable ipv6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        # Value is a string field
        value: '1'
        sysctl_set: true
        state: present
        reload: true
    - name: Deploy dhclient.conf
      copy:
        dest: /etc/dhcp/dhclient.conf
        src: files/dhclient.conf
        backup: true
        mode: 0644
        owner: root
        group: root
      notify: restart networking

- name: Configure PostgreSQL
  hosts: meta-role_postgresql_server
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - local.pgdg
    - geerlingguy.postgresql
    - local.timescaledb

- name: Bootstrap client basic configuration
  hosts: meta-role_client
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - local.pgdg
  tasks:
    - name:
      apt:
        name: "{{ item }}"
      with_items: "{{ postgresql_client_packages }}"

- name: Bootstrap tsbs
  hosts: meta-subrole_tsbs
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - andrewrothstein.go
  tasks:
    - name: Configure GOPATH
      copy:
        dest: /etc/profile.d/gopath.sh
        content: |
          export GOPATH=$HOME/go/
          export PATH="${GOPATH}/bin:${PATH}"
        owner: root
        group: root
        mode: '0644'
