---
- name: Bootstrap basic
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - brianshumate.consul
  tasks:
    - name: Disable ipv6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        # Value is a string field
        value: '1'
        sysctl_set: true
        state: present
        reload: true
