---
- name: Bootstrap basic
  hosts: all
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - local.common-packages
    - brianshumate.consul
  tasks:
    - name: Disable ipv6
      sysctl:
        name: net.ipv6.conf.all.disable_ipv6
        # Value is a string field
        value: '1'
        sysctl_set: true
        state: present
        reload: true

- name: Configure PostgreSQL
  hosts: meta-role_postgresql_server
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - local.pgdg
    - geerlingguy.postgresql
    - local.timescaledb
