---
consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:9100"
        interval: "10s"
  - name: "nginx-exporter"
    id: "nginx-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:8080"
        interval: "10s"
  - name: "promscale-exporter"
    id: "promscale-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - http: "http://{{ private_ip }}:9201/healthz"
        interval: "10s"
  - name: "promscale"
    id: "promscale"
    address: "{{ private_ip }}"
    port: 9201
    checks:
      - http: "http://{{ private_ip }}:9201/healthz"
        interval: "10s"
    tags:
      - node
  - name: "promtail"
    id: "promtail"
    address: "127.0.0.1"
    port: 9080
    checks:
      - tcp: "localhost:9080"
        interval: "10s"
  - name: "promtail-exporter"
    id: "promtail-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:9080"
        interval: "10s"
