---
promscale_bin_version: 0.2.0
promscale_limitnofile: 1048576
promscale_cfg:
  PROMSCALE_DB_HOST: rw.timescaledb.service.consul
  PROMSCALE_DB_PORT: 3000
  PROMSCALE_DB_NAME: timescale
  PROMSCALE_DB_PASSWORD: timescale
  PROMSCALE_DB_USER: timescale
  TS_WEB_ENABLE_ADMIN_API: 1
  PROMSCALE_LOG_LEVEL: error
  # Let's pick a random id in positive not null smallint
  PROMSCALE_LEADER_ELECTION_PG_ADVISORY_LOCK_ID: "{{ range(1, 32767) |random(seed=ansible_hostname) }}"
  # Setting PROMETHEUS_TIMEOUT just above prometheus scrape interval
  PROMSCALE_LEADER_ELECTION_PG_ADVISORY_LOCK_PROMETHEUS_TIMEOUT: 16s
