---

consul_template_template_templates:
  - src: "templates/haproxy-timescale.ctmpl.j2"
    dest: "haproxy.ctmpl"
    cmd: "systemctl reload consul-template.service"
    perms: "0600"
    backup: "true"
    wait: "2s"
