---
postgresql_users:
  - name: tsbs
    password: tsbs
    role_attr_flags: SUPERUSER
  - name: timescale
    password: timescale
    role_attr_flags: SUPERUSER

postgresql_databases:
  - name: tsbs
    owner: tsbs
  - name: timescale
    owner: timescale

postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '10.94.3.0/24', auth_method: md5}

consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 9100
    checks:
      - tcp: "{{ private_ip }}:9100"
        interval: "10s"
  - name: "postgresql"
    id: "postgresql"
    address: "{{ private_ip }}"
    port: 5432
    checks:
      - tcp: "{{ private_ip }}:5432"
        interval: "10s"
  - name: "tsbs"
    id: "tsbs"
    address: "{{ private_ip }}"
    port: 5432
    checks:
      - tcp: "{{ private_ip }}:5432"
        interval: "10s"
  - name: "timescale"
    id: "timescale"
    address: "{{ private_ip }}"
    port: 5432
    checks:
      - tcp: "{{ private_ip }}:5432"
        interval: "10s"
