---
consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:9100"
        interval: "10s"
  - name: "haproxy-exporter"
    id: "haproxy-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - http: http://localhost:9101/health
        interval: "10s"
