---
haproxy_exporter_version: 0.12.0
haproxy_exporter_tarball_checksum: sha1:128e0b69113325c4f857595819bc836f4697fbc8
haproxy_exporter_options:
  - --haproxy.scrape-uri=unix:/run/haproxy.sock
  - --web.listen-address=localhost:9101
