---
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.39.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_validate
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.20.0
    hooks:
      - id: yamllint
  - repo: https://github.com/ansible/ansible-lint.git
    rev: v4.2.0
    hooks:
      - id: ansible-lint
