---
consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:9100"
        interval: "10s"
  - name: "nginx-exporter"
    id: "nginx-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:8080"
        interval: "10s"
  - name: "prometheus-exporter"
    id: "prometheus-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:8080"
        interval: "10s"
  - name: "prometheus"
    id: "prometheus"
    address: "{{ private_ip }}"
    port: 9090
    checks:
      - tcp: "{{ private_ip }}:9090"
        interval: "10s"
