---
prometheus_version: 2.26.0
prometheus_web_external_url: "http://{{ ansible_host }}:9090"
prometheus_storage_retention: 1d
prometheus_storage_retention_size: 250GB
prometheus_remote_write:
  - url: http://node.promscale.service.dc1.consul:9201/write
    name: timescaledb
    remote_timeout: 30s
    # https://www.alibabacloud.com/help/doc-detail/114516.htm
    # Let's aim for ~1M sample/sec
    queue_config:
      capacity: 10000
      max_samples_per_send: 1000
      max_shards: 192
      min_shards: 4
      batch_send_deadline: 30s
  - url: http://rw.victoriametrics.service.dc1.consul:8480/insert/0/prometheus
    name: victoriametrics
prometheus_remote_read:
  - url: http://node.promscale.service.dc1.consul:9201/read
    name: timescaledb
  - url: http://ro.victoriametrics.service.dc1.consul:8481/select/0/prometheus
    name: victoriametrics
prometheus_scrape_configs:
  - job_name: node-exporter
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [node-exporter]
  - job_name: node-exporter-bench
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/*.yml
  - job_name: victoriametrics
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [victoriametrics]
  - job_name: postgresql
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [postgresql-exporter]
  - job_name: haproxy
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [haproxy]
  - job_name: prometheus
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [prometheus]
  - job_name: promscale
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [promscale]
  - job_name: promtail
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [promtail]
  - job_name: loki
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [loki]
  - job_name: etcd
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [etcd]
