---
prometheus_version: 2.21.0
prometheus_web_external_url: "http://{{ ansible_host }}:9090"
prometheus_remote_write:
  - url: http://rw.promscale:9201/write
  - url: http://rw.victoriametrics:8480/insert/0/prometheus
prometheus_remote_read:
  - url: http://ro.promscale:9201/read
  - url: http://ro.victoriametrics:8481/select/0/prometheus
prometheus_scrape_configs:
  - job_name: node-exporter
    metrics_path: /node_exporter/metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [node-exporter]
    file_sd_configs:
      - files:
          - /etc/prometheus/file_sd/*.yml
  - job_name: nginx-exporter
    metrics_path: /nginx_exporter/metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [nginx-exporter]
  - job_name: victoriametrics-exporter
    metrics_path: /victoriametrics_exporter/metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [victoriametrics-exporter]
  - job_name: postgresql-exporter
    metrics_path: /postgresql_exporter/metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [postgresql-exporter]
  - job_name: haproxy-exporter
    metrics_path: /haproxy_exporter/metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [haproxy-exporter]
  - job_name: prometheus-exporter
    metrics_path: /prometheus_exporter/metrics
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [prometheus-exporter]
