---
consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:9100"
        interval: "10s"
  - name: "victoriametrics-exporter"
    id: "victoriametrics-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - http: "http://{{ private_ip }}:8481/health"
        interval: "10s"
  - name: "victoriametrics"
    id: "victoriametrics"
    address: "{{ private_ip }}"
    port: 8481
    checks:
      - http: "http://{{ private_ip }}:8481/health"
        interval: "10s"
    tags:
      - select
