---
nginx_config_http_template:
  app:
    servers:
      main:
        reverse_proxy:
          locations:
            victoriametrics_exporter:
              location: /victoriametrics_exporter/
              proxy_cache: exporter
              proxy_pass: "http://localhost:8481/"
              proxy_cache_background_update: false
              proxy_cache_lock: true
              proxy_cache_min_uses: 1
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host
