---
private_ip: "{{ ansible_all_ipv4_addresses | ipaddr('10.0.0.0/8') | first }}"
sysctl_overwrite:
  net.ipv6.conf.all.disable_ipv6: 1
common_packages:
  - apt-transport-https
  - ca-certificates
  - cron
  - curl
  - diffutils
  - dnsutils
  - git
  - gnupg
  - htop
  - iftop
  - iotop
  - net-tools
  - nmap
  - telnet

ansible_ssh_user: debian

consul_node_role: client
# TODO: /!\ This is not secure do not use this in production at anytime
consul_raw_key: "y5vPZpzeALhaTlc2c5rJbzrplx34A/afro9SAMhiTK4="
consul_version: 1.8.4
consul_group_name: meta-role_consul_server
# FIXME: this will not be always eth1 when we use ONLY private network
consul_iface: eth1
consul_recursors:
  - 213.186.33.99
  - 8.8.8.8
consul_dnsmasq_enable: true
consul_dnsmasq_bind_interfaces: true
consul_dnsmasq_listen_addresses:
  - 127.0.0.1

node_exporter_version: 1.0.1
node_exporter_web_listen_address: "{{ private_ip }}:9100"
node_exporter_enabled_collectors:
  - cpu
  - diskstats
  - filesystem
  - loadavg
  - meminfo
  - netclass
  - netdev
  - netstat
  - processes
  - systemd
  - tcpstat

consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 9100
    checks:
      - tcp: "{{ private_ip }}:9100"
        interval: "10s"

postgresql_version: 12
