---
victoriametrics_vmselect_cache_dir: "/usr/local/bin/victoria-cache"
victoriametrics_vmselect_memory_allowed_percent: "60"
victoriametrics_vmselect_service_args: ""  # Add extra variables here . Found more options with vmselect-prod --help

consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:9100"
        interval: "10s"
  - name: "victoriametrics-exporter"
    id: "victoriametrics-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - http: http://localhost:8481/health
        interval: "10s"
  - name: "victoriametrics"
    id: "victoriametrics"
    address: "{{ private_ip }}"
    port: 8481
    checks:
      - http: http://localhost:8481/health
        interval: "10s"
    tags:
      - select

nginx_config_http_template:
  app:
    servers:
      main:
        reverse_proxy:
          locations:
            victoriametrics_exporter:
              location: /victoriametrics_exporter/
              proxy_cache: exporter
              proxy_pass: "http://localhost:8481/"
              proxy_cache_background_update: false
              proxy_cache_lock: true
              proxy_cache_min_uses: 1
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host
