---
prometheus_version: 2.21.0
prometheus_web_external_url: "http://{{ ansible_host }}:9090"
prometheus_remote_write:
  - url: http://timescale-prometheus.node:9201/write
  - url: http://victoriametrics-rw:8480/insert/0/prometheus
prometheus_remote_read:
  - url: http://promscale:9201/read
  - url: http://victoriametrics-ro:8481/select/0/prometheus
prometheus_scrape_configs:
  - job_name: consul
    relabel_configs:
      - source_labels: [__meta_consul_node]
        target_label: hostname
      - source_labels: [__meta_consul_node]
        target_label: instance
      - source_labels: [__meta_consul_dc]
        target_label: dc
    consul_sd_configs:
      - server: 'localhost:8500'
        services: [node-exporter, vminsert, vmselect, vmstorage, postgresql-exporter]
