---
grafana_security:
  admin_user: admin
  # TODO: /!\ This is not secure do not use this in production at anytime
  admin_password: enter_your_secure_password

grafana_datasources:
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://timescale-prometheus.node:9201"
    isDefault: true

consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 9100
    checks:
      - tcp: "{{ private_ip }}:9100"
        interval: "10s"
  - name: "grafana"
    id: "grafana"
    address: "{{ private_ip }}"
    port: 3000
    checks:
      - http: http://localhost:3000/
        interval: "10s"
