---

# defaults file for consul-template
consul_template_version: "0.25.1"
consul_template_use_systemd: true
consul_template_templates:
  - name: "haproxy.ctmpl"
    dest: "/etc/haproxy/haproxy.cfg"
    cmd: "systemctl reload haproxy.service"
    perms: "0600"
    backup: "true"
    wait: "2s"

haproxy_exporter_version: 0.12.0
haproxy_exporter_tarball_checksum: sha1:128e0b69113325c4f857595819bc836f4697fbc8
haproxy_exporter_options:
  - --haproxy.scrape-uri=unix:/run/haproxy.sock

consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 9100
    checks:
      - tcp: "{{ private_ip }}:9100"
        interval: "10s"
  - name: "haproxy-exporter"
    id: "haproxy-exporter"
    address: "{{ private_ip }}"
    port: 9101
    checks:
      - http: http://localhost:9101/health
        interval: "10s"
