---
cluster_id: 0
patroni_users:
  - name: timescale
    password: timescale
    role_attr_flags: SUPERUSER

patroni_databases:
  - name: timescale
    owner: timescale
    extensions:
      - name: timescaledb

consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 9100
    checks:
      - tcp: "{{ private_ip }}:9100"
        interval: "10s"
  - name: "postgresql"
    id: "postgresql"
    address: "{{ private_ip }}"
    port: 5432
    checks:
      - tcp: "{{ private_ip }}:5432"
        interval: "10s"
  - name: "tsbs"
    id: "tsbs"
    address: "{{ private_ip }}"
    port: 5432
    checks:
      - tcp: "{{ private_ip }}:5432"
        interval: "10s"
  - name: "timescale"
    id: "timescale"
    address: "{{ private_ip }}"
    port: 5432
    checks:
      - tcp: "{{ private_ip }}:5432"
        interval: "10s"
