---
postgresql_python_library: python3-psycopg2
postgresql_version: 12
# Otherwise it will default to __postgresql_version
postgresql_data_dir: "/var/lib/postgresql/{{ postgresql_version }}/main"
postgresql_config_path: "/etc/postgresql/{{ postgresql_version }}/main"
postgresql_global_config_options:
  - option: shared_preload_libraries
    value: timescaledb
  - option: timescaledb.telemetry_level
    value: "off"
  - option: listen_addresses
    # This will configure postgresql to listen on the first ip in the given subnet
    # This could be even more specific if we use the subnet dedicated to dbms for example
    value: "{{ ansible_all_ipv4_addresses | ipaddr('10.0.0.0/8') | first }}"

timescaledb_packages:
  - "timescaledb-postgresql-{{ postgresql_version }}"
  - timescaledb-tools
