---
consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 9100
    checks:
      - tcp: "{{ private_ip }}:9100"
        interval: "10s"
  - name: "victoriametrics"
    id: "victoriametrics"
    address: "{{ private_ip }}"
    port: 8482
    checks:
      - http: "http://{{ private_ip }}:8482/health"
        interval: "10s"
    tags:
      - storage
  - name: "promtail"
    id: "promtail"
    address: "{{ private_ip }}"
    port: 9080
    checks:
      - tcp: "{{ private_ip }}:9080"
        interval: "10s"
