---
victoriametrics_vmstorage_data_dir: "/usr/local/bin/victoria-storage"
victoriametrics_vmstorage_retention_period: "24"
victoriametrics_vmstorage_memory_allowed_percent: "60"  # 60 is the default value
# Add extra variables here .Found more options withvmstorage-prod --help
# yamllint disable-line rule:line-length
victoriametrics_vmstorage_service_args: "-httpListenAddr={{ private_ip }}:8482 -vminsertAddr={{ private_ip }}:8400 -vmselectAddr={{ private_ip }}:8401"
