---
- name: Copy the timescale_prometheus systemd service file
  template:
    src: timescale_prometheus.service.j2
    dest: /etc/systemd/system/timescale_prometheus.service
    owner: root
    group: root
    mode: 0644
  notify: restart timescale_prometheus

- name: Copy the timescale_prometheus systemd env file
  template:
    src: timescale_prometheus.cfg.j2
    dest: "{{ timescale_prometheus_cfg_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart timescale_prometheus
