---
consul_node_role: client
# TODO: /!\ This is not secure do not use this in production at anytime
consul_raw_key: "y5vPZpzeALhaTlc2c5rJbzrplx34A/afro9SAMhiTK4="
consul_version: 1.8.4
consul_group_name: meta-role_consul_server
# FIXME: this will not be always eth1 when we use ONLY private network
consul_iface: eth1
consul_recursors:
  - 213.186.33.99
  - 8.8.8.8
consul_dnsmasq_enable: true
consul_dnsmasq_bind_interfaces: true
consul_dnsmasq_listen_addresses:
  - 127.0.0.1

consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:9100"
        interval: "10s"
  - name: "nginx-exporter"
    id: "nginx-exporter"
    address: "{{ private_ip }}"
    port: 8888
    checks:
      - tcp: "localhost:8080"
        interval: "10s"
