---
grafana_admin_user: admin
# TODO: /!\ This is not secure do not use this in production at anytime
grafana_admin_password: enter_your_secure_password

grafana_url: http://grafana.service.dc1.consul:3000
