---
sysctl_overwrite:
  net.ipv6.conf.all.disable_ipv6: 1

  # With the following settings, your application will detect dead TCP
  # connections after 120 seconds (60s + 10s + 10s + 10s + 10s + 10s + 10s).
  net.ipv4.tcp_keepalive_intvl: 10
  net.ipv4.tcp_keepalive_probes: 6
  net.ipv4.tcp_keepalive_time: 60

ssh_permit_root_login: without-password
ssh_kex:
  - curve25519-sha256@libssh.org
  - diffie-hellman-group-exchange-sha256

ssh_ciphers:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

ssh_macs:
  - umac-128-etm@openssh.com
  - umac-64-etm@openssh.com
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - umac-128@openssh.com
  - umac-64@openssh.com
  - hmac-sha2-512
  - hmac-sha2-256

ssh_host_key_algorithms:
  - ssh-ed25519-cert-v01@openssh.com
  - ssh-rsa-cert-v01@openssh.com
  - ssh-ed25519
  - ssh-rsa
