---
nginx_config_cleanup: true

nginx_config_http_template_enable: true
nginx_config_http_template:
  app:
    template_file: http/default.conf.j2
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/
    proxy_cache:
      proxy_cache_path:
        - path: /tmp/cache
          # Having a large number of files in a single directory can slow down
          # file access, so we recommend a two‑level directory hierarchy for
          # most deployments
          levels: "1:2"
          inactive: 1m
          max_size: 2g
          use_temp_path: false
          keys_zone:
            name: exporter
            # 10‑MB zone configured in the example can store data for about
            # 80,000 keys
            size: 10m
    servers:
      main:
        listen:
          listen_localhost:
            port: 8888
            ip: "{{ private_ip }}"
        server_name: localhost
        access_log:
          - name: main
            location: /var/log/nginx/access.log
        reverse_proxy:
          locations:
            node_exporter:
              location: /node_exporter/
              proxy_cache: exporter
              proxy_pass: "http://localhost:9100/"
              proxy_cache_background_update: false
              proxy_cache_lock: true
              proxy_cache_min_uses: 1
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host
            nginx_exporter:
              location: /nginx_exporter/
              proxy_cache: exporter
              proxy_pass: "http://localhost:9113/"
              proxy_cache_background_update: false
              proxy_cache_lock: true
              proxy_cache_min_uses: 1
              proxy_set_header:
                header_host:
                  name: Host
                  value: $host

# Enable status reporting so we can expose nginx metrics
nginx_config_status_enable: true
nginx_config_status_port: 127.0.0.1:8080

nginx_exporter_version: 0.8.0
nginx_exporter_tarball_checksum: sha256:fce51ce62650186f9f4cb3ff13fa4b36ffc2980058a63bccdb471c929c078e50
nginx_exporter_options:
  - '-nginx.scrape-uri=http://localhost:8080/nginx_status'
  - '-web.listen-address=localhost:9113'
