---
node_exporter_version: 1.1.2
node_exporter_enabled_collectors:
  - cpu
  - diskstats
  - filesystem
  - loadavg
  - meminfo
  - netclass
  - netdev
  - netstat
  - processes
  - systemd
  - tcpstat
