---
# Add extra variables here . Found more options with vminsert-prod --help
victoriametrics_vminsert_service_args: "-replicationFactor=3 -httpListenAddr={{ private_ip }}:8480"
victoriametrics_vminsert_memory_allowed_percent: "60"
