---
consul_services:
  - name: "node-exporter"
    id: "node-exporter"
    address: "{{ private_ip }}"
    port: 9100
    checks:
      - tcp: "{{ private_ip }}:9100"
        interval: "10s"
  - name: "loki"
    id: "loki"
    address: "{{ private_ip }}"
    port: "{{ loki_listen_port }}"
    checks:
      - http: "http://{{ private_ip }}:{{ loki_listen_port }}/ready"
        interval: "10s"
  - name: "promtail"
    id: "promtail"
    address: "{{ private_ip }}"
    port: 9080
    checks:
      - tcp: "{{ private_ip }}:9080"
        interval: "10s"
