---
grafana_security:
  admin_user: admin
  # TODO: /!\ This is not secure do not use this in production at anytime
  admin_password: enter_your_secure_password

grafana_datasources:
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://prometheus:9090"
    isDefault: true

  - name: "VictoriaMetrics"
    type: "prometheus"
    access: "proxy"
    url: "http://ro.victoriametrics:8481/select/0/prometheus"

  - name: "promscale"
    type: "prometheus"
    access: "proxy"
    url: "http://ro.promscale:9201"

  - name: "cortex"
    type: "prometheus"
    access: "proxy"
    url: "http://query-frontend.cortex:9009/prometheus"

  - name: "timescaledb"
    type: "postgres"
    sslmode: "require"
    access: "proxy"
    url: "ro.timescaledb:4000"
    database: "timescale"
    user: "timescale"
    password: "timescale"
    jsonData:
      sslmode: require
      timescaledb: true
      postgresVersion: 1200

  - name: "loki"
    type: "loki"
    access: "proxy"
    url: "http://loki.service.dc1.consul:3100"

grafana_plugins:
  - grafana-worldmap-panel
  - grafana-piechart-panel
  - digiapulssi-breadcrumb-panel

grafana_dashboards:
  # Prometheus Node Exporter Full
  - dashboard_id: 1860
    revision_id: 21
    datasource: Prometheus
  # Prometheus - cluster
  - dashboard_id: 11176
    revision_id: 8
    datasource: Prometheus
  # Postgres Overview
  - dashboard_id: 455
    revision_id: 2
    datasource: Prometheus
  # HAproxy Servers | HAproxy
  - dashboard_id: 367
    revision_id: 3
    datasource: Prometheus
  # HAproxy Backend | HAproxy
  - dashboard_id: 364
    revision_id: 3
    datasource: Prometheus
  # HAproxy Frontend | HAproxy
  - dashboard_id: 361
    revision_id: 3
    datasource: Prometheus
  # Prometheus 2.0 Overview
  - dashboard_id: 3662
    revision_id: 2
    datasource: Prometheus

grafana_dashboards_dir: files/grafana/dashboards/


# See:
# https://github.com/opstrace/opstrace/tree/be59d0eb45d55045bea1e06f494d0a00280af9cd/packages/controller/src/resources/monitoring/system/dashboards
