---
grafana_security:
  admin_user: admin
  # TODO: /!\ This is not secure do not use this in production at anytime
  admin_password: enter_your_secure_password

grafana_datasources:
  - name: "VictoriaMetrics"
    type: "prometheus"
    access: "proxy"
    url: "http://ro.victoriametrics:8481/select/0/prometheus"
    isDefault: true

  - name: "promscale"
    type: "prometheus"
    access: "proxy"
    url: "http://ro.promscale:9201"

  - name: "timescaledb"
    type: "postgres"
    sslmode: "require"
    access: "proxy"
    url: "ro.timescaledb:4000"
    database: "timescale"
    user: "timescale"
    password: "timescale"
    jsonData:
      sslmode: require
      timescaledb: true
      postgresVersion: 1200

grafana_plugins:
  - grafana-worldmap-panel
  - grafana-piechart-panel
  - digiapulssi-breadcrumb-panel

grafana_dashboards:
  # Prometheus Node Exporter Full
  - dashboard_id: 1860
    revision_id: 21
    datasource: VictoriaMetrics
  # VictoriaMetrics - cluster
  - dashboard_id: 11176
    revision_id: 8
    datasource: VictoriaMetrics
  # Postgres Overview
  - dashboard_id: 455
    revision_id: 2
    datasource: VictoriaMetrics
  # HAproxy Servers | HAproxy
  - dashboard_id: 367
    revision_id: 3
    datasource: VictoriaMetrics
  # HAproxy Backend | HAproxy
  - dashboard_id: 364
    revision_id: 3
    datasource: VictoriaMetrics
  # HAproxy Frontend | HAproxy
  - dashboard_id: 361
    revision_id: 3
    datasource: VictoriaMetrics
  # Prometheus 2.0 Overview
  - dashboard_id: 3662
    revision_id: 2
    datasource: VictoriaMetrics
