---
nginx_exporter_version: 0.9.0
nginx_exporter_tarball_checksum: sha256:469851e5705a83e9bba9eb402a7484d196293826470f4f66b1d2a4a1074b6599
nginx_exporter_platform_suffix: "linux_amd64"
nginx_exporter_signature: "nginx-prometheus-exporter_{{ nginx_exporter_version }}_{{ nginx_exporter_platform_suffix }}"
nginx_exporter_options:
  - '-nginx.scrape-uri=http://localhost:8080/nginx_status'
  - '-web.listen-address={{ private_ip }}:9113'
