---
- name: Copy the promscale systemd service file
  template:
    src: promscale.service.j2
    dest: /etc/systemd/system/promscale.service
    owner: root
    group: root
    mode: 0644
  notify: restart promscale

- name: Copy the promscale systemd env file
  template:
    src: promscale.cfg.j2
    dest: "{{ promscale_cfg_path }}"
    owner: root
    group: root
    mode: 0644
  notify: restart promscale
  when: promscale_manage_cfg
